"resource/ui/mainmenuoverride-safemode.res"
{
  "SafeMode"
  {
    "controlName"  "EditablePanel"
    "fieldName"    "SafeMode"
    "xpos"         "rs1"
    "ypos"         "120"
    "wide"         "200"
    "tall"         "f0"
    "zpos"         "1000"
    "visible"      "1"
    "enabled"      "1"

    "ToggleVM"
    {
      "controlName"                "CExButton"
      "fieldName"                  "ToggleVM"
      "xpos"                       "0"
      "ypos"                       "s0"
      "wide"                       "f0"
      "tall"                       "13"
      "visible"                    "1"
      "enabled"                    "1"
      "proportionaltoparent"       "1"
      "sound_depressed"            "UI/buttonclick.wav"
      "actionsignallevel"          "2"
      "command"                    "engine incrementvar r_drawviewmodel 0 1 1"
      "font"                       "DebugOverlay"
      "textAlignment"              "east"
      "labelText"                  "r_drawviewmodel"
      "paintbackground"            "0"
      "paintborder"                "0"
      "defaultFgColor_override"    "White"
      "armedFgColor_override"      "Main Menu Labels"
      "depressedFgColor_override"  "Main Menu Labels"
    }

    "ToggleMinVM"
    {
      "controlName"                "CExButton"
      "fieldName"                  "ToggleMinVM"
      "xpos"                       "0"
      "ypos"                       "s1"
      "wide"                       "f0"
      "tall"                       "13"
      "visible"                    "1"
      "enabled"                    "1"
      "proportionaltoparent"       "1"
      "sound_depressed"            "UI/buttonclick.wav"
      "actionsignallevel"          "2"
      "command"                    "engine incrementvar cl_use_min_viewmodels 0 1 1"
      "font"                       "DebugOverlay"
      "textAlignment"              "east"
      "labelText"                  "cl_use_min_viewmodels"
      "paintbackground"            "0"
      "paintborder"                "0"
      "defaultFgColor_override"    "White"
      "armedFgColor_override"      "Main Menu Labels"
      "depressedFgColor_override"  "Main Menu Labels"
    }

    "ToggleScoreboard"
    {
      "controlName"                "CExButton"
      "fieldName"                  "ToggleScoreboard"
      "xpos"                       "0"
      "ypos"                       "s2"
      "wide"                       "f0"
      "tall"                       "13"
      "visible"                    "1"
      "enabled"                    "1"
      "proportionaltoparent"       "1"
      "sound_depressed"            "UI/buttonclick.wav"
      "actionsignallevel"          "2"
      "command"                    "engine incrementvar cl_hud_minmode 0 1 1"
      "font"                       "DebugOverlay"
      "textAlignment"              "east"
      "labelText"                  "cl_hud_minmode"
      "paintbackground"            "0"
      "paintborder"                "0"
      "defaultFgColor_override"    "White"
      "armedFgColor_override"      "Main Menu Labels"
      "depressedFgColor_override"  "Main Menu Labels"
    }
  }
}
